### ISSUE TITLE
Allow specific quantities of an item to be ordered.

### ISSUE THREAD

**Issue by mcole24** [Wheeler-GWC/farm2tablerevised#7]
Currently, ordering an item orders its entire quantity. So if we have 10 cans of corn, and we only want maybe 2 cans to go to any one student, we would enter in 5 different items and just specify a quantity of 2 each.

We need functionality to allow users to select a quantity lesser than or equal to the maximum for that item. When an order is placed, we need to then update the row to reduce the quantity accordingly.

**Comment by polyrtm** [comment]
Maybe add a put a dropdown menu on the order row instead of a checkbox?

**Comment by mcole24** [comment]
@JackFly26 yes, that would be a good solution. Of course, you would need to set the range of values in the dropdown to match the available quantity, but that shouldn't be difficult.
